### ISSUE TITLE
Example scene

### ISSUE THREAD

**Issue by NewNodeGames** [derrideanauthor/GodotEasyAStarPathfinding#1]
Can you upload a working example or more detailed instructions? I tried with your script following the instructions without success.

**Comment by derrideanauthor** [comment]
Hi @NewNodeGames . I've uploaded and example. It should explain things pretty well. Its super simple.

**Comment by derrideanauthor** [comment]
@NewNodeGames I seemed to have left a step out of the description about instantiating the script. Please check the readme again :)

**Comment by NewNodeGames** [comment]
Hey thanks for update but I don't have luck. I'm using 3.1 dev and got this error when executed the scene: Parser error: Too many arguments for 'get_path()' call. Expected at most 0

**Comment by derrideanauthor** [comment]
Hi @NewNodeGames Are you talking about the example I uploaded? If so, I wouldn't recommend 3.1 since it is still unstable, use 3.0.6 (the error you noted doesn't make sense to me, that function has 3 arguments). Let me know when you get it working :)

**Comment by NewNodeGames** [comment]
I found the problem origin: get_path() is a built-in function on Godot 3.1. I changed for _get_path() and now the project run without any issue. Thanks.

**Comment by derrideanauthor** [comment]
@NewNodeGames great. I will rename the function :)
